services:
  app1:
    container_name: app1
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - 8080:3001
    env_file:
      - ./app1/.env

  app2:
    container_name: app2
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - 8081:3002
    env_file:
      - ./app2/.env